### ISSUE TITLE
Running IFC.js in a Java WebEngine browser

### ISSUE THREAD

**Issue by quarto-zz** [tomvandig/web-ifc-three#7]
I have been trying to run IFC.js in a Java WebEngine browser.  I have compressed the IFC.js demo folder into a WAR file and successfully started up a Jetty local sever and IFC.js runs happily on localhost:8080 in a regular browser.  In the Java browser the index page displays and I can select a model but no model or 3D space appears.   Do any of you have any ideas on what additional HTML or browser settings are used in a regular browser to make this work, that may not be set in my Java WebEngine browser?
I have run out of things to try.  The Java WebEngine is clearly not running the JavaScript in the referenced bundle.js, even though WebEngine should happily run JavaScript in the HTML page.

[sample_Java.txt](https://github.com/tomvandig/web-ifc-three/files/6558967/sample_Java.txt)

My username on Discord is SilentBob.

**Comment by tomvandig** [comment]
You can try to catch some logging output from the WebEngine, which might tell you what's going wrong. I suspect either some file path is not found, or WebAssembly is simply not supported. This page has more info: https://stackoverflow.com/a/49077436/6207777

However, I have tried googling and can't find if the Java WebEngine does or does not support WebAssembly. I think it should, since it is based on WebKit. However, it is not explicitly stated, and if it does not support WebAssembly then IFC.js will never run properly.

**Comment by tomvandig** [comment]
Looks like WebGL is not supported at all even though its running on WebKit. So IFC.js won't work inside the WebEngine unfortunately.  Kudo's to IFC.js discord for finding this out. 

You could try to embed chrome into java, with https://github.com/chromiumembedded/java-cef , or use the native browser directly, but I think both options are complicated.
